### ISSUE TITLE
按了下一章或前一张后出现div的background-image属性丢失的情况

### ISSUE THREAD

**Issue by kylin-z** [hilongjw/vue-slide#2]
styleCompute (obj) {
            let opacityValue = 0
            if( (obj.origin + obj.current) == 0) opacityValue = 1

```
        obj.style = {
            'transform' : `translateX(${obj.origin + obj.current}%)`
        }
    }
```

这里改成
 styleCompute (obj) {
            let opacityValue = 0
            if( (obj.origin + obj.current) == 0) opacityValue = 1

```
        obj.style.transform = `translateX(${obj.origin + obj.current}%)`
    }
```

就显示正常了

**Comment by hilongjw** [comment]
感谢反馈，我会在下一次提交里修复这个问题
