### ISSUE TITLE
移动端(主要是安卓)过度动画有点问题

### ISSUE THREAD

**Issue by kylin-z** [hilongjw/vue-slide#3]
![image](https://cloud.githubusercontent.com/assets/12540239/14224243/90e22a50-f8c8-11e5-809c-e47583940d30.png)

这里把-webkit-transition-duration单独拿出来写可以解决，缩写似乎没有用

**Comment by hilongjw** [comment]
soga, 我测试到也是在某些app的 webview 中会没有过渡，谢谢反馈
