### ISSUE TITLE
有迁移vue2.0的计划吗？

### ISSUE THREAD

**Issue by paraofheaven** [hilongjw/vue-slide#8]
--**我看现在父子组件都是通过broadcast和dispatch来传播的，vue2.0里面好像不建议这样做了，有迁移的计划吗？

**Comment by hilongjw** [comment]
@paraofheaven 打算之后合并到 RadonUI 2.0 重构的项目中，计划是下周会开始。

**Comment by hilongjw** [comment]
@paraofheaven 已经支持vue2.0
